### ISSUE TITLE
Child controller doesn't response/work inside parent view

### ISSUE THREAD

**Issue by shahnawaz** [mohuk/generator-ng-super#9]
Steps to reproduce:

// use ng-super commands to do this
1. Create a module with its controller (parent),
2. Create another controller (child) in that module, and link it inside the view of parent controller (or however you like). To create parent/child relation
3. just perform any operation on child controller, it doesn't work

but if you change the name of the child controller it starts working..

**Comment by mohuk** [comment]
This usually happens when the Angular DI pool has duplicate entries against a single identifier. For example:

1) A module has 2 controllers by the same name
2) Two separate modules have controllers by the same name but are dependent on another module which is trying to access that controller i.e. Module A has HelloCtrl and Module B has HelloCtrl but both modules are made dependent of another i.e. 

``` javascript
angular.module('C', ['A', 'B']);
```

then trying to access HelloCtrl from within Module C would fail because the DI pool will contain 2 entries against HelloCtrl, one for each A and B.

As far as my knowledge goes, Angular Components are not name spaced by their modules in the DI pool and hence such conditions would fail.

Renaming works because it is now registered by a different identifier in the DI pool.

Make sure you dont have duplicates and it would then work fine.
